version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: